version: '3'
services:
  node-1:
    build: .
    image: ion-dtn:latest
    volumes:
      - $PWD/docker_resources:/resources:ro
      - $PWD/configs/spaceapps:/tmp/configs:ro
    command: |
      bash -c "ln -s /dev/stdout ion.log & ionstart -I /tmp/configs/tcp.1.rc & tail -f /dev/null & wait"
    networks:
      default:
      ion_net:
        ipv4_address: 10.1.1.2

  node-2:
    build: .
    image: ion-dtn:latest
    volumes:
      - $PWD/docker_resources:/resources:ro
      - $PWD/configs/spaceapps:/tmp/configs:ro
    command: |
      bash -c "ln -s /dev/stdout ion.log & ionstart -I /tmp/configs/tcp.2.rc & tail -f /dev/null & wait"
    networks:
      default:
      ion_net:
        ipv4_address: 10.1.1.3

networks:
  ion_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.1.0/24
